CREATE TABLE houses (
    link varchar(255),
    house_photo varchar(255),
    street varchar(255),
    post_index varchar(16),
    city varchar(64),
    sell_period int,
    build_year int,
    energy_class varchar(16),
    house_area int,
    terittory_area int,
    house_type varchar(64),
    amount_rooms int,
    price bigint,
    price_per_meter int,
    price_tax int,
    price_changes varchar(16),
    first_payment int,
);